### ISSUE TITLE
Can Dat Desktop be installed on Windows?

### ISSUE THREAD

**Issue by ambrt** [datproject/dat-desktop#122]
I'm trying to "npm install" on windows but i get errors:
```
prebuild WARN install No prebuilt binaries found (target=v4.5.0 arch=x64 platform=win32)
'make' is not recognized as an internal or external command,

Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
 ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"

```

**Comment by ambrt** [comment]
I installed http://gnuwin32.sourceforge.net/packages/make.htm

and i get
```
prebuild WARN install No prebuilt binaries found (target=v4.5.0 arch=x64 platform=win32)
make: Interrupt/Exception caught (code = 0xc00000fd, addr = 0x4227d3)
prebuild ERR! build Error: make  failed with exit code 255
prebuild ERR! build     at Object.exports.spawnFailed (C:\Users\User\Downloads\dat-desktop-master\dat-desktop\node_modules\sodium-prebuilt\node_modules\prebuild\error.js:31:10)
prebuild ERR! build     at ChildProcess.<anonymous> (C:\Users\User\Downloads\dat-desktop-master\dat-desktop\node_modules\sodium-prebuilt\node_modules\prebuild\util.js:116:14)
prebuild ERR! build     at emitTwo (events.js:87:13)
prebuild ERR! build     at ChildProcess.emit (events.js:172:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

```
prebuild ERR! build error
prebuild ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
prebuild ERR! stack     at ChildProcess.onExit (C:\Users\User\Downloads\dat-desktop-master\dat-desktop\node_modules\node-gyp\lib\build.js:276:23)
prebuild ERR! stack     at emitTwo (events.js:87:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:172:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
prebuild ERR! not ok
prebuild ERR! build Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
prebuild ERR! build     at ChildProcess.onExit (C:\Users\User\Downloads\dat-desktop-master\dat-desktop\node_modules\node-gyp\lib\build.js:276:23)
prebuild ERR! build     at emitTwo (events.js:87:13)
prebuild ERR! build     at ChildProcess.emit (events.js:172:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by yoshuawuyts** [comment]
Not yet. We're working on prebuilt versions of Dat's native dependencies so
we can have it work smoothly on Windows too. See
https://github.com/datproject/dat/issues/581

**Comment by ambrt** [comment]
Ok, thank you for answer.
