### ISSUE TITLE
Write unit tests for models

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#251]
As per #155 we should probably also unit test our models. I'm thinking starting with reducers, and moving onto effects & subscriptions. This should hopefully add some degree of robustness to our app. No guarantees though, but I think besides moving code out of the project this might be the most helpful way to stabilize our app.

### todos
- [x] setup unit testing framework
- [ ] write a few basic tests

**Comment by karissa** [comment]
Yea! IMO it's good to start with unit tests for things that have broken the most through the dev process, like deleting a dat and progress bar for example

**Comment by yoshuawuyts** [comment]
We talked about this on a call and figured it'd be cool to setup a unit testing framework, and add tests as we run into possible regressions.

**Comment by juliangruber** [comment]
progress has started here: https://github.com/datproject/dat-desktop/compare/add/test-framework?expand=1

**Comment by juliangruber** [comment]
current error to fix, when requiring the repos model as well:

```
TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at TypeError (native)
    at Object.<anonymous> (/Users/julian/dev/datproject/dat-desktop/node_modules/base-elements/node_modules/bel/node_modules/on-load/index.js:21:12)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/julian/dev/datproject/dat-desktop/node_modules/base-elements/node_modules/bel/index.js:3:14)
```

**Comment by juliangruber** [comment]
@yoshuawuyts the test framework is set up now, waiting for the choo5 migration I guess until we add tests?

**Comment by yoshuawuyts** [comment]
Yeah, let's wait for a lil bit on that haha

**Comment by yoshuawuyts** [comment]
Just reviewed the framework; gist of it LGTM.

**Comment by juliangruber** [comment]
ok, removing from milestone then

**Comment by yoshuawuyts** [comment]
We got unit tests in for choo 5 recently #328 - closing!
