### ISSUE TITLE
Cannot find module "browserify" on Debian jessie

### ISSUE THREAD

**Issue by jayrbolton** [datproject/dat-desktop#331]
Downloaded and tried:

```
chmod a+x dat-desktop-1.1.1-x86_64.AppImage
./dat-desktop-1.1.1-x86_64.AppImage
```

And got:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'browserify'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/tmp/.mount_6mtrOd/usr/bin/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/.mount_6mtrOd/usr/bin/resources/app.asar/lib/browserify.js:1:99)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

Are there any further instructions for running this `.AppImage` file? I can try it with a different window manager in a minute and see if that works better.

**Comment by juliangruber** [comment]
Interesting, I can't reproduce this in my ubuntu setup. Did you get to try with a different window manager?

**Comment by juliangruber** [comment]
closing for lack of feedback
